# ============================================================================
# Playbook: Filesystem Check Site Playbook
# ============================================================================
#
# Description:
#   Main playbook for automated filesystem health scanning across multiple
#   Linux hosts. This playbook orchestrates the filesystem_check role to
#   perform read-only filesystem health checks and generate comprehensive
#   HTML reports on remote hosts, then collect them back to the control node.
#
# Purpose:
#   - Automate filesystem health scanning across multiple hosts
#   - Perform read-only checks (xfs_scrub for XFS, fsck -n for ext2/3/4)
#   - Collect disk space and inode usage information
#   - Generate detailed HTML health reports
#   - Collect reports back to control node for centralized analysis
#
# Workflow:
#   1. Play 1: Execute filesystem check role on all target hosts (generate reports)
#   2. Play 2: Collect reports from all target hosts to control node
#   3. Play 3: Display final summary and confirmation
#
# Usage:
#   ansible-playbook filesystem_check_site.yml -i inventory
#
# Author: GCG AAP SSA Team + v3.01 20260217
#
# License:
#   📜 License Type: End User License Agreement (EULA)
#   🔒 Authorization: Subscription-based License
#
# ============================================================================

---
# ============================================================================
# Play 1: Execute Filesystem Check on All Hosts
# ============================================================================
# This play runs the filesystem_check role on all target hosts to perform
# read-only filesystem health checks and generate HTML reports. The role
# will check all mounted filesystems (excluding virtual and special FS)
# and create a report file on each host.
- name: Execute filesystem check and generate reports on all hosts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    # ========================================================================
    # OS Compatibility Validation
    # ========================================================================
    - name: Validate OS compatibility (RHEL/CentOS 7/8/9 only)
      ansible.builtin.assert:
        that:
          - ansible_os_family == "RedHat"
          - ansible_distribution in ['RedHat', 'CentOS']
          - ansible_distribution_major_version in ['7', '8', '9']
        fail_msg: "Unsupported operating system. This playbook is only available for RHEL 7/8/9 and CentOS 7/8/9. Current OS: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
        success_msg: "OS compatibility check passed: {{ ansible_distribution }} {{ ansible_distribution_major_version }}"
      tags:
        - validation
        - always

    - name: Display OS information for debugging
      ansible.builtin.debug:
        msg:
          - "Distribution: {{ ansible_distribution }}"
          - "Version: {{ ansible_distribution_version }}"
          - "Major Version: {{ ansible_distribution_major_version }}"
      tags:
        - validation
        - debug

    # ========================================================================
    # Execute Filesystem Check Role
    # ========================================================================
    - name: Include filesystem_check role
      ansible.builtin.include_role:
        name: filesystem_check
      tags:
        - check
        - always

# ============================================================================
# Play 2: Collect Reports from All Hosts
# ============================================================================
# This play collects the generated HTML report files from all target hosts
# back to the control node for centralized analysis and storage.
- name: Collect filesystem check reports from all hosts
  hosts: all
  gather_facts: false

  vars:
    # Define variables needed for this play (not loaded from role)
    report_base_path: "/tmp"
    collection_dest_path: "/tmp"

  tasks:
    # ========================================================================
    # Validate Collection Parameters
    # ========================================================================
    - name: Validate collection destination path
      ansible.builtin.assert:
        that:
          - collection_dest_path is defined
          - collection_dest_path | length > 0
        fail_msg: "collection_dest_path must be a valid directory path"
        success_msg: "Collection destination path validated: {{ collection_dest_path }}"
      tags:
        - validation
        - always

    - name: Display collection configuration for debugging
      ansible.builtin.debug:
        msg:
          - "Report source path: {{ report_base_path }}/{{ inventory_hostname }}-fs-report-*.html"
          - "Collection destination: {{ collection_dest_path }}"
      tags:
        - collection
        - debug

    # ========================================================================
    # Find and Fetch Report Files
    # ========================================================================
    - name: Find report files on remote host
      ansible.builtin.find:
        paths: "{{ report_base_path }}"
        patterns: "{{ inventory_hostname }}-fs-report-*.html"
        file_type: file
      register: report_files
      tags:
        - collection
        - always

    - name: Display found report files for debugging
      ansible.builtin.debug:
        msg:
          - "Found {{ report_files.files | length }} report file(s)"
          - "Files: {{ report_files.files | map(attribute='path') | list }}"
      when: report_files.files | length > 0
      tags:
        - collection
        - debug

    - name: Fetch report file from remote host
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "{{ collection_dest_path }}/"
        flat: yes
      loop: "{{ report_files.files }}"
      when: report_files.files | length > 0
      register: fetch_result
      tags:
        - collection
        - always

    - name: Display fetch result for debugging
      ansible.builtin.debug:
        msg:
          - "Report file fetched: {{ item.changed | default(false) }}"
          - "Destination: {{ collection_dest_path }}/{{ item.dest | basename }}"
      loop: "{{ fetch_result.results | default([]) }}"
      when: fetch_result.results is defined
      tags:
        - collection
        - debug

# ============================================================================
# Play 3: Final Summary and Confirmation
# ============================================================================
# This play runs on localhost to display a final summary and confirmation
# that all reports have been successfully collected.
- name: Display final summary and confirmation
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    collection_dest_path: "/tmp"

  tasks:
    # ========================================================================
    # Final Summary
    # ========================================================================
    - name: Display completion summary
      ansible.builtin.debug:
        msg:
          - "✅ All filesystem check reports have been successfully collected!"
          - "Reports are stored in the control node's {{ collection_dest_path }}/ directory."
          - "Report file naming format: <hostname>-fs-report-<timestamp>.html"
          - "You can review individual reports in a web browser for detailed analysis."
      tags:
        - summary
        - always

    - name: Display next steps
      ansible.builtin.debug:
        msg:
          - "Next steps:"
          - "  1. Review individual reports: open {{ collection_dest_path }}/<hostname>-fs-report-*.html in a web browser"
          - "  2. Check for filesystems with issues (marked with ⚠️)"
          - "  3. Review disk space and inode usage statistics"
          - "  4. Take corrective actions as needed (repair operations require maintenance windows)"
      tags:
        - summary
        - always

